---
# kibana

- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Get kibana.8.6.2
  ansible.builtin.get_url:  
    url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/k/kibana/kibana-8.6.2-amd64.deb
    dest: /home/martynova/

- name: Install kibana
  apt:
    deb: /home/martynova/kibana-8.6.2-amd64.deb 

- name: Systemctl daemon reload
  systemd:
    daemon_reload: true
    name: kibana.service
    state: started

- name: Copy config file for kibana
  template:
    src: ./templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644

- name: Systemctl enable  kibana
  systemd:
    name: kibana.service
    state: restarted
